version: '2'
services:
    master_001:
        build: mysql-relication
        environment:
             - MYSQL_ROOT_PASSWORD=123456
    slave_001:
        build: mysql-relication
        environment:
             - MASTER_HOST=master_001
             - MYSQL_ROOT_PASSWORD=123456
        links :
             - master_001
    haproxy:
        build : haproxy
        links:
             - master_001
             - slave_001
        ports:
             - "8080:8080"
              - "8080:8080"
